"""Provider contracts shared by managed and self-hosted deployments."""
from __future__ import annotations

from typing import Any, Mapping, Protocol, Sequence


class DatabaseProvider(Protocol):
    """Small provider-neutral persistence contract used by Ghostea services."""

    def select(self, table: str, query: Mapping[str, Any]): ...
    def insert(self, table: str, payload: Any, return_rows: bool = False): ...
    def upsert(self, table: str, payload: Any): ...
    def update(self, table: str, payload: Any, query: Mapping[str, Any]): ...
    def delete(self, table: str, query: Mapping[str, Any]): ...
    def check_tables(self, tables: Sequence[str]): ...
    def count(self, table: str, query: Mapping[str, Any] | None = None): ...

    def close(self): ...


class StorageProvider(Protocol):
    def put(self, key: str, data: bytes, content_type: str | None = None): ...
    def get(self, key: str) -> bytes: ...
    def delete(self, key: str): ...
    def exists(self, key: str) -> bool: ...
